title:            Brian Fitzgerald
tagline:          Let's talk.
description:      
#Comment out url when working locally to resolve base urls correctly
#url: http://brianfitzgerald.github.io

# Owner/author information
owner:
  name:           Brian Fitzgerald
  avatar:         avatar.png
  bio:            "Writer and Programmer"
  email:          cooldude242@gmail.com
  twitter:        brianrovski        
  github:         brianfitzgerald       
  instagram:           
  dribbble:       
  disqus:         roborovskis
  # Plug in your disqus shortname!


# Links to include in top navigation
# For external links add external: true
links:
  - title: Who's Brian?
    url: /about
  - title: Github
    url: https://github.com/brianfitzgerald
    external: true
  - title: Résumé
    url: http://brianfitzgerald.neocities.org/resume-printable.html
    external: true
  - title: Contact Me
    url: /contact

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter:    true
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]